---
version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sale-hook
    ports:
      - 5000:5000
    environment:
      - API_KEY
      - SG_API
      - TEMPLATE_ID
      - URL
    volumes:
      - ./data:/data
    restart: unless-stopped